export const user = {
    id: 1,
    avatar: '',
    name: 'John Doe',
    email: 'martin@gmail.com',
    phone: '123456789',
    address: 'Calle Falsa 123',
    role: "admin",
    status: true,
    birthDate: "1990-05-15",
    age: 34,
    weight: 75, // kg
    height: 178, // cm
    profession: "Ingeniero de software",
    trainingDays: ["Lunes", "Miércoles", "Viernes"],
    trainingHours: "07:00 - 08:00",
    sport: ["Fútbol", "Ciclismo"],
    goal: "Mejorar resistencia y perder grasa",
    injuries: ["Ninguna"], // lesiones previas
    medicalConditions: ["Ninguna"],
    experience: "Intermedia",
    motivation: ["Prepararse para una maratón"],
}

export const users = [
    {
        id: 1,
        documento: '38294756',
        avatar: '',
        name: 'John Doe',
        email: 'martin1@gmail.com',
        phone: '123456789',
        address: 'Calle Falsa 123',
        role: "teacher",
        status: true,
        birthDate: "1990-05-15",
        age: 34,
        weight: 75, // kg
        height: 178, // cm
        profession: "Ingeniero de software",
        trainingDays: ["Lunes", "Miércoles", "Viernes"],
        trainingHours: "07:00 - 08:00",
        sport: ["Fútbol", "Ciclismo"],
        goal: "Mejorar resistencia y perder grasa",
        injuries: ["Ninguna"], // lesiones previas
        medicalConditions: ["Ninguna"],
        experience: "Intermedia",
        motivation: ["Prepararse para una maratón"],
    }, {
        id: 2,
        documento: '27483920',
        avatar: '',
        name: 'Martin Gomez',
        email: 'martin2@gmail.com',
        phone: '123456789',
        address: 'Calle Falsa 123',
        role: "teacher",
        status: true,
        birthDate: "1990-05-15",
        age: 34,
        weight: 75, // kg
        height: 178, // cm
        profession: "Ingeniero de software",
        trainingDays: ["Lunes", "Miércoles", "Viernes"],
        trainingHours: "07:00 - 08:00",
        sport: ["Fútbol", "Ciclismo"],
        goal: "Mejorar resistencia y perder grasa",
        injuries: ["Ninguna"], // lesiones previas
        medicalConditions: ["Ninguna"],
        experience: "Intermedia",
        motivation: ["Prepararse para una maratón"],
    },{
        id: 3,
        documento: '41029384',
        avatar: '',
        name: 'Carlos Ruiz',
        email: 'carlos.teacher@gmail.com',
        phone: '123456789',
        address: 'Calle Falsa 123',
        role: "teacher",
        status: false,
        birthDate: "1990-05-15",
        age: 34,
        weight: 75, // kg
        height: 178, // cm
        profession: "Ingeniero de software",
        trainingDays: ["Lunes", "Miércoles", "Viernes"],
        trainingHours: "07:00 - 08:00",
        sport: ["Fútbol", "Ciclismo"],
        goal: "Mejorar resistencia y perder grasa",
        injuries: ["Ninguna"], // lesiones previas
        medicalConditions: ["Ninguna"],
        experience: "Intermedia",
        motivation: ["Prepararse para una maratón"],
    }, {
        id: 4,
        documento: '35678123',
        avatar: '',
        name: 'Ana Trainer',
        email: 'ana.trainer@gmail.com',
        phone: '123456789',
        address: 'Calle Falsa 123',
        role: "trainer",
        status: true,
        birthDate: "1990-05-15",
        age: 34,
        weight: 75, // kg
        height: 178, // cm
        profession: "Ingeniero de software",
        trainingDays: ["Lunes", "Miércoles", "Viernes"],
        trainingHours: "07:00 - 08:00",
        sport: ["Fútbol", "Ciclismo"],
        goal: "Mejorar resistencia y perder grasa",
        injuries: ["Ninguna"], // lesiones previas
        medicalConditions: ["Ninguna"],
        experience: "Intermedia",
        motivation: ["Prepararse para una maratón"],
        assignedTeacherId: 1,
    }, {
        id: 5,
        documento: '29837465',
        avatar: '',
        name: 'Pedro Trainer',
        email: 'pedro.trainer@gmail.com',
        phone: '123456789',
        address: 'Calle Falsa 123',
        role: "trainer",
        status: true,
        birthDate: "1990-05-15",
        age: 34,
        weight: 75, // kg
        height: 178, // cm
        profession: "Ingeniero de software",
        trainingDays: ["Lunes", "Miércoles", "Viernes"],
        trainingHours: "07:00 - 08:00",
        sport: ["Fútbol", "Ciclismo"],
        goal: "Mejorar resistencia y perder grasa",
        injuries: ["Ninguna"], // lesiones previas
        medicalConditions: ["Ninguna"],
        experience: "Intermedia",
        motivation: ["Prepararse para una maratón"],
        assignedTeacherId: 1,
    }, {
        id: 6,
        documento: '40928374',
        avatar: '',
        name: 'Laura Trainer',
        email: 'laura.trainer@gmail.com',
        phone: '123456789',
        address: 'Calle Falsa 123',
        role: "trainer",
        status: false,
        birthDate: "1990-05-15",
        age: 34,
        weight: 75, // kg
        height: 178, // cm
        profession: "Ingeniero de software",
        trainingDays: ["Lunes", "Miércoles", "Viernes"],
        trainingHours: "07:00 - 08:00",
        sport: ["Fútbol", "Ciclismo"],
        goal: "Mejorar resistencia y perder grasa",
        injuries: ["Ninguna"], // lesiones previas
        medicalConditions: ["Ninguna"],
        experience: "Intermedia",
        motivation: ["Prepararse para una maratón"],
        assignedTeacherId: 2,
    }, {
        id: 7,
        documento: '11223344',
        avatar: '',
        name: 'Admin Principal',
        email: 'admin@effort-habit.com',
        phone: '123456789',
        address: 'Calle Falsa 123',
        role: "admin",
        status: true,
        birthDate: "1990-05-15",
        age: 34,
        weight: 75, // kg
        height: 178, // cm
        profession: "Administrador",
        trainingDays: [],
        trainingHours: "",
        sport: [],
        goal: "Gestionar la plataforma",
        injuries: ["Ninguna"],
        medicalConditions: ["Ninguna"],
        experience: "Experto",
        motivation: ["Mejorar la plataforma"],
    }, {
        id: 8,
        documento: '55667788',
        avatar: '',
        name: 'Jorge Trainer',
        email: 'jorge.trainer@gmail.com',
        phone: '123456789',
        address: 'Calle Falsa 123',
        role: "trainer",
        status: true,
        birthDate: "1990-05-15",
        age: 34,
        weight: 75, // kg
        height: 178, // cm
        profession: "Ingeniero de software",
        trainingDays: ["Lunes", "Miércoles", "Viernes"],
        trainingHours: "07:00 - 08:00",
        sport: ["Fútbol", "Ciclismo"],
        goal: "Mejorar resistencia y perder grasa",
        injuries: ["Ninguna"],
        medicalConditions: ["Ninguna"],
        experience: "Intermedia",
        motivation: ["Prepararse para una maratón"],
        assignedTeacherId: 2,
    },
]